#!/usr/bin/env python3
"""
build_icons.py — generate Android VectorDrawables from the Sora brand SVGs.

WHY THIS EXISTS
---------------
`branding/*.svg` are the design source of truth, but they are NOT valid Android
drawables. VectorDrawable supports only `<path>`; the brand SVGs use four
features it cannot express:

  1. `<text>`      — no text support. Converted to outline paths via
                     extract_glyph.py (Noto Serif JP, OFL 1.1).
  2. `<line>`      — no line primitive. Converted to a one-segment path.
  3. `<clipPath>`  — needs explicit `pathData`; `rx` on a `<rect>` is not
                     understood, so the squircle is written as an arc path.
  4. `opacity`     — mapped to `fillAlpha` / `strokeAlpha`.

Rather than hand-convert once and leave un-reproducible XML in res/, this
script regenerates every drawable from the documented geometry. Re-run it after
any branding change:

    python3 tools/svg2vd/build_icons.py

DEVIATIONS FROM THE SOURCE SVGs (also logged in DECISIONS.md)
-------------------------------------------------------------
* Foreground layer is transparent. The source foreground painted its own sky
  gradient into a 76dp squircle while the background painted a full-bleed
  gradient over 108dp. Same colours, different spans, so the ramps did not
  align and a squircle seam was visible. Standard adaptive-icon practice is a
  transparent foreground over the gradient background; it also lets launcher
  parallax work, since the layers move independently.
* Horizon inset from x=18..90 to x=20..88. The guaranteed-visible region of an
  adaptive icon is a 72dp *circle*; at y=63 that circle spans only x=19.1..88.9,
  so the original round caps were clipped on circular-mask launchers.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
RES_DRAWABLE = REPO_ROOT / "app" / "src" / "main" / "res" / "drawable"
EXTRACT = Path(__file__).resolve().parent / "extract_glyph.py"

# Font files are pulled from the @fontsource/noto-serif-jp npm package at
# generation time. They are never committed and never shipped in the APK.
FONT_DIR = Path("/tmp/fontprobe/node_modules/@fontsource/noto-serif-jp/files")
FONT_300 = FONT_DIR / "noto-serif-jp-japanese-300-normal.woff"
FONT_400 = FONT_DIR / "noto-serif-jp-japanese-400-normal.woff"

# --- Brand palette ---------------------------------------------------------
SKY_TOP = "#5BA3D0"
SKY_MID = "#4A90E2"  # brand seed, also the Material 3 static-palette seed
SKY_BOT = "#2C5AA0"

# --- Shared geometry (108dp adaptive-icon canvas) --------------------------
# Floating 16:9 frame, x=30 y=30 w=48 h=27 rx=2, written as an arc path.
FRAME = (
    "M32,30 L76,30 A2,2 0 0 1 78,32 L78,55 A2,2 0 0 1 76,57 "
    "L32,57 A2,2 0 0 1 30,55 L30,32 A2,2 0 0 1 32,30 Z"
)
# Horizon, inset to survive circular masking (see module docstring).
HORIZON = "M20,63 L88,63"
# Squircle used for the sky fill, x=16 y=16 w=76 h=76 rx=18.
SQUIRCLE = (
    "M34,16 L74,16 A18,18 0 0 1 92,34 L92,74 A18,18 0 0 1 74,92 "
    "L34,92 A18,18 0 0 1 16,74 L16,34 A18,18 0 0 1 34,16 Z"
)


def glyph(font: Path, size: float, x: float, y: float, anchor: str = "middle") -> str:
    """Run extract_glyph.py and return VectorDrawable pathData for 空."""
    if not font.exists():
        raise SystemExit(
            f"error: font not found at {font}\n"
            "Fetch it first:\n"
            "  mkdir -p /tmp/fontprobe && cd /tmp/fontprobe && npm init -y \\\n"
            "    && npm i @fontsource/noto-serif-jp"
        )
    result = subprocess.run(
        [
            sys.executable, str(EXTRACT),
            "--font", str(font), "--char", "空",
            "--size", str(size), "--x", str(x), "--y", str(y),
            "--anchor", anchor,
        ],
        capture_output=True, text=True, check=True,
    )
    return result.stdout.strip()


HEADER = "<!-- GENERATED by tools/svg2vd/build_icons.py from branding/{src} — do not edit by hand. -->"


def sky_gradient_path(path_data: str, y1: float, y2: float, bottom_alpha: str = "") -> str:
    """A filled path whose fill is the vertical sky gradient.

    `bottom_alpha` is an optional 2-digit hex alpha ("D9" == 0.85) applied to
    the final stop, matching `stop-opacity` in the source SVG. VectorDrawable
    colours are #AARRGGBB, so the alpha is prefixed to the RGB value.
    """
    bottom = f"#{bottom_alpha}{SKY_BOT.lstrip('#')}" if bottom_alpha else SKY_BOT
    return f"""    <path android:pathData="{path_data}">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="54" android:startY="{y1}"
                android:endX="54" android:endY="{y2}">
                <item android:offset="0.0" android:color="{SKY_TOP}" />
                <item android:offset="0.55" android:color="{SKY_MID}" />
                <item android:offset="1.0" android:color="{bottom}" />
            </gradient>
        </aapt:attr>
    </path>"""


def write(name: str, body: str) -> None:
    RES_DRAWABLE.mkdir(parents=True, exist_ok=True)
    (RES_DRAWABLE / name).write_text(body, encoding="utf-8")
    print(f"  wrote app/src/main/res/drawable/{name}")


def build_foreground() -> None:
    """Adaptive icon foreground: transparent, mark only (see docstring)."""
    watermark = glyph(FONT_300, 38, 54, 50)
    signature = glyph(FONT_400, 10, 80, 83)
    write("ic_launcher_foreground.xml", f"""<?xml version="1.0" encoding="utf-8"?>
{HEADER.format(src="ic_launcher_foreground.svg")}
<!--
    Adaptive icon FOREGROUND. 108x108dp canvas; only the centre 72dp is
    guaranteed visible - the launcher masks the rest to a circle, squircle or
    rounded square. Fully transparent outside the mark so the gradient
    background layer shows through and parallax works.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">

    <!-- Faint 空 watermark in the upper sky -->
    <path
        android:pathData="{watermark}"
        android:fillColor="#FFFFFF"
        android:fillAlpha="0.08" />

    <!-- Horizon - golden-ratio division of the safe zone -->
    <path
        android:pathData="{HORIZON}"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="0.8"
        android:strokeLineCap="round"
        android:strokeAlpha="0.7" />

    <!-- Floating 16:9 frame - the "window" into content -->
    <path
        android:pathData="{FRAME}"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="1.5" />

    <!-- 空 signature, lower-right of the safe zone -->
    <path
        android:pathData="{signature}"
        android:fillColor="#FFFFFF"
        android:fillAlpha="0.55" />
</vector>
""")


def build_background() -> None:
    write("ic_launcher_background.xml", f"""<?xml version="1.0" encoding="utf-8"?>
{HEADER.format(src="ic_launcher_background.svg")}
<!-- Adaptive icon BACKGROUND: full-bleed sky gradient. Brand seed {SKY_MID}. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">

{sky_gradient_path("M0,0 L108,0 L108,108 L0,108 Z", 0, 108)}
</vector>
""")


def build_monochrome() -> None:
    """Android 13+ themed icon. Single colour; system tints the alpha mask."""
    watermark = glyph(FONT_300, 38, 54, 50)
    signature = glyph(FONT_400, 10, 80, 83)
    write("ic_launcher_monochrome.xml", f"""<?xml version="1.0" encoding="utf-8"?>
{HEADER.format(src="ic_launcher_monochrome.svg")}
<!--
    Adaptive icon MONOCHROME layer (Android 13+ themed icons). Rendered as a
    pure alpha mask and tinted to the user's wallpaper palette, so every
    element is one colour. The watermark alpha is raised from 0.08 to 0.3
    (as in the source SVG) so it survives the alpha-mask conversion.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">

    <path
        android:pathData="{watermark}"
        android:fillColor="#FFFFFF"
        android:fillAlpha="0.3" />

    <path
        android:pathData="{HORIZON}"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="0.8"
        android:strokeLineCap="round" />

    <path
        android:pathData="{FRAME}"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="1.5" />

    <path
        android:pathData="{signature}"
        android:fillColor="#FFFFFF" />
</vector>
""")


def build_splash() -> None:
    """Simplified mark for the Android 12+ SplashScreen API."""
    signature = glyph(FONT_400, 10, 80, 83)
    write("ic_splash.xml", f"""<?xml version="1.0" encoding="utf-8"?>
{HEADER.format(src="ic_splash.svg")}
<!--
    SplashScreen icon (windowSplashScreenAnimatedIcon). Simplified relative to
    the launcher mark: watermark dropped, strokes bolder, so it stays crisp
    while the system scales it inside the 288dp splash window. Content sits
    within x/y 16..92 (~70% of the canvas), inside the visible region.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">

    <!-- Sky fill, clipped to the squircle safe zone -->
{sky_gradient_path(SQUIRCLE, 16, 92, "D9")}

    <path
        android:pathData="{HORIZON}"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="1"
        android:strokeLineCap="round"
        android:strokeAlpha="0.7" />

    <path
        android:pathData="{FRAME}"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="2" />

    <path
        android:pathData="{signature}"
        android:fillColor="#FFFFFF"
        android:fillAlpha="0.55" />
</vector>
""")


def build_notification() -> None:
    """24dp status-bar icon. Android forces this to a white alpha mask."""
    write("ic_notification.xml", f"""<?xml version="1.0" encoding="utf-8"?>
{HEADER.format(src="ic_notification.svg")}
<!--
    Notification small icon, 24x24dp. Android renders this as a flat alpha
    mask - any colour is discarded - so it is the frame plus a horizon tick
    only. The kanji is far too fine to read at 24dp and would turn to mush.
    Used by the Media3 playback notification (Phase 5).
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">

    <!-- Floating 16:9 frame, x=2 y=3 w=20 h=11 rx=1.5 -->
    <path
        android:pathData="M3.5,3 L20.5,3 A1.5,1.5 0 0 1 22,4.5 L22,12.5 A1.5,1.5 0 0 1 20.5,14 L3.5,14 A1.5,1.5 0 0 1 2,12.5 L2,4.5 A1.5,1.5 0 0 1 3.5,3 Z"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="1.5" />

    <!-- Horizon tick -->
    <path
        android:pathData="M6,18 L18,18"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="1"
        android:strokeLineCap="round" />
</vector>
""")


def main() -> int:
    print("Generating VectorDrawables from branding SVGs...")
    build_background()
    build_foreground()
    build_monochrome()
    build_splash()
    build_notification()
    print("Done. Remember: mipmap-anydpi-v26/ic_launcher.xml ties the layers together.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
